[package]
name = "mmu-table-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
zynq7000-rt = { path = "../../firmware/zynq7000-rt", default-features = false }
zynq7000-mmu = { path = "../../firmware/zynq7000-mmu", features = ["tools"] }
