[package]
name = "probe-rs-test"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
probe-rs = { path = "../../probe-rs/probe-rs" }
defmt-decoder = { version = "1" }
anyhow = { version = "1" }
